### ISSUE TITLE
uninitialized constant Rack::Test::Utils (NameError)

### ISSUE THREAD

**Issue by openface** [zipmark/rspec_api_documentation#178]
Following the README, I've added rspec_api_documention (4.3.0) to my Gemfile and bundle installed, added the acceptance test, but getting this error trying to generate docs:

```
$ rake docs:generate
/u/jhines/.rvm/rubies/ruby-2.1.1/bin/ruby -I/u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/lib:/u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-support-3.0.3/lib -S /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/exe/rspec spec/acceptance/burts_spec.rb --format RspecApiDocumentation::ApiFormatter
Generating API Docs
/u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rack-test-0.6.2/lib/rack/test.rb:27:in `<class:Session>': uninitialized constant Rack::Test::Utils (NameError)
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rack-test-0.6.2/lib/rack/test.rb:25:in `<module:Test>'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rack-test-0.6.2/lib/rack/test.rb:11:in `<module:Rack>'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rack-test-0.6.2/lib/rack/test.rb:10:in `<top (required)>'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rack-test-0.6.2/lib/rack/test/utils.rb:2:in `<module:Rack>'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rack-test-0.6.2/lib/rack/test/utils.rb:1:in `<top (required)>'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/dsl/endpoint.rb:3:in `require'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/dsl/endpoint.rb:3:in `<top (required)>'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/dsl.rb:3:in `require'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/dsl.rb:3:in `<top (required)>'
    from /u/jhines/apps/burt-api-server/spec/acceptance/burts_spec.rb:2:in `require'
    from /u/jhines/apps/burt-api-server/spec/acceptance/burts_spec.rb:2:in `<top (required)>'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `load'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `each'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:97:in `setup'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:85:in `run'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:70:in `run'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:38:in `invoke'
    from /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/exe/rspec:4:in `<main>'
/u/jhines/.rvm/rubies/ruby-2.1.1/bin/ruby -I/u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/lib:/u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-support-3.0.3/lib -S /u/jhines/.rvm/gems/ruby-2.1.1@burt_api_server/gems/rspec-core-3.0.3/exe/rspec spec/acceptance/burts_spec.rb --format RspecApiDocumentation::ApiFormatter failed
```

This is Rails 4.0.6.

**Comment by reiz** [comment]
@openface I don't get it. What did you do exactly to solve this problem?

**Comment by hut8** [comment]
@reiz You've probably figured this out by now but since I just ran into the same issue, the docs say to do this:

```
require 'spec_helper'
require 'rspec_api_documentation/dsl'

resource "Orders" do
  get "/orders" do
    example "Listing orders" do
      do_request

      status.should == 200
    end
  end
end
```

But I needed to change `spec_helper` to `rails_helper` for it to work, since `spec_helper` doesn't include rails-related stuff (`rails_helper` requires `spec_helper`, though).

**Comment by reiz** [comment]
@hut8 Yes. I resolved it already. But thank you anyway :)

**Comment by Fedcomp** [comment]
@reiz but some people from google did not :) thanks @hut8
