### ISSUE TITLE
When using raw_post and Content-Type application/json rspec errors out

### ISSUE THREAD

**Issue by scmyers11** [zipmark/rspec_api_documentation#194]
Failure/Error: Unable to find matching line from backtrace
     ActionDispatch::ParamsParser::ParseError:
       795: unexpected token at 'grant_type=client_credentials&client_id=d512debf7d49186443ebc27b1f50308939618859dfb37717d4b6fe2b403ae759&client_secret=50e820e5eb5a0b684112cf074cb752df799ebf7f204cd8f60dcb97377a11bddc'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/params_parser.rb:53:in `rescue in parse_formatted_parameters'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/params_parser.rb:32:in `parse_formatted_parameters'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/params_parser.rb:23:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/flash.rb:254:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/cookies.rb:560:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.1.0/lib/active_record/query_cache.rb:36:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:82:in `run_callbacks'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.0/lib/rails/rack/logger.rb:38:in `call_app'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.0/lib/rails/rack/logger.rb:20:in `block in call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:68:in `tagged'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.0/lib/rails/rack/logger.rb:20:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.1.0/lib/action_dispatch/middleware/static.rb:64:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/honeybadger-1.16.5/lib/honeybadger/rack/error_notifier.rb:43:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/honeybadger-1.16.5/lib/honeybadger/rack/user_feedback.rb:24:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/honeybadger-1.16.5/lib/honeybadger/rack/user_informer.rb:13:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.0/lib/rails/engine.rb:514:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.1.0/lib/rails/application.rb:144:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-test-0.6.3/lib/rack/test.rb:67:in `post'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/rack_test_client.rb:38:in `do_request'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/client_base.rb:42:in `process'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/client_base.rb:16:in `post'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/dsl/endpoint.rb:58:in `do_request'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec_api_documentation-4.3.0/lib/rspec_api_documentation/dsl/endpoint.rb:16:in `block in example_request'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example.rb:148:in `instance_exec'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example.rb:148:in `block in run'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example.rb:208:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example.rb:208:in `block (2 levels) in <class:Procsy>'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-rails-3.0.1/lib/rspec/rails/adapters.rb:68:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example.rb:292:in `instance_exec'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example.rb:292:in `instance_exec'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/hooks.rb:430:in `block (2 levels) in run'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example.rb:208:in `call'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example.rb:208:in `block (2 levels) in <class:Procsy>'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/hooks.rb:428:in `run'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/hooks.rb:485:in `run'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example.rb:301:in `with_around_example_hooks'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example.rb:145:in `run'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example_group.rb:494:in `block in run_examples'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example_group.rb:490:in `map'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example_group.rb:490:in `run_examples'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example_group.rb:457:in `run'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example_group.rb:458:in `block in run'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example_group.rb:458:in `map'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/example_group.rb:458:in `run'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:112:in `block (2 levels) in run_specs'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:112:in `map'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:112:in `block in run_specs'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/reporter.rb:54:in `report'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:108:in `run_specs'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:86:in `run'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:70:in `run'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:38:in `invoke'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.0/exe/rspec:4:in `<top (required)>'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/bin/rspec:23:in `load'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/bin/rspec:23:in `<main>'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
     # /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

I am trying to pass a fairly large json hash to a post method.  The tests pass when I don't set the Content-Type, but if it is set I get the above error.  I would like to set the content type to json so that the output documentation can include that the body needs to be json.  Any help would be appreciated.  If you need to see my code let me know and I will post something.  Sorry for the very long stack trace.

**Comment by scmyers11** [comment]
For anyone that is having this issue in the future.  Whenever you pass params to `raw_post`, and set the content-type to `application/json` you have to call `#to_json` on the params that you pass.
