### ISSUE TITLE
Some specs and features fails

### ISSUE THREAD

**Issue by ceritium** [zipmark/rspec_api_documentation#234]
Some specs and features fails but looks like that fails because some kind of order in the output of the test tools.

```bash
/home/ceritium/.rbenv/versions/2.1.6/bin/ruby -I/home/ceritium/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib:/home/ceritium/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rspec-support-3.3.0/lib /home/ceritium/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 53294
............................................................................................................................................................................................................................FF.......................F..............................

Failures:

  1) RspecApiDocumentation::ApiFormatter output with passing examples should list the generated docs
     Failure/Error: expect(output.string.split($/)).to eq([
       
       expected: ["Generating API Docs", "  Orders", "    * Ordering a cup of coffee", "    * Updating an order", "    * Viewing an order"]
            got: ["Generating API Docs", "  Orders", "    * Viewing an order", "    * Updating an order", "    * Ordering a cup of coffee"]
       
       (compared using ==)
     # ./spec/api_formatter_spec.rb:66:in `block (4 levels) in <top (required)>'

  2) RspecApiDocumentation::ApiFormatter output with failing examples should indicate failures
     Failure/Error: expect(output.string.split($/)).to eq([
       
       expected: ["Generating API Docs", "  Orders", "    * Ordering a cup of coffee", "    ! Updating an order (FAILED)", "    ! Viewing an order (FAILED)"]
            got: ["Generating API Docs", "  Orders", "    ! Viewing an order (FAILED)", "    ! Updating an order (FAILED)", "    * Ordering a cup of coffee"]
       
       (compared using ==)
     # ./spec/api_formatter_spec.rb:85:in `block (4 levels) in <top (required)>'

  3) RspecApiDocumentation::Configuration.add_setting should allow the default setting to be a lambda
     Failure/Error: expect(configuration.another_setting).to eq("default")
       
       expected: "default"
            got: nil
       
       (compared using ==)
     # ./spec/configuration_spec.rb:27:in `block (3 levels) in <top (required)>'

Finished in 0.51638 seconds (files took 0.56639 seconds to load)
276 examples, 3 failures

Failed examples:

rspec ./spec/api_formatter_spec.rb:64 # RspecApiDocumentation::ApiFormatter output with passing examples should list the generated docs
rspec ./spec/api_formatter_spec.rb:83 # RspecApiDocumentation::ApiFormatter output with failing examples should indicate failures
rspec ./spec/configuration_spec.rb:25 # RspecApiDocumentation::Configuration.add_setting should allow the default setting to be a lambda

Randomized with seed 53294
```

Link for the cucumber output https://gist.github.com/ceritium/52dee02775e913f10d96

**Comment by oestrich** [comment]
Closing, the most recent runs on Travis are passing.
