### ISSUE TITLE
Failure/Error: do_request

### ISSUE THREAD

**Issue by korumo12** [zipmark/rspec_api_documentation#321]
Why?
```
    $ rake docs:generate
    # ...........................

    Generating API Docs
      Orders
      GET /orders
        ! Listing orders (FAILED)

    Failures:

      1) Orders GET /orders Listing orders
         Failure/Error: do_request
         
         NoMethodError:
           undefined method `call' for nil:NilClass
           Did you mean?  caller
         # /home/alex/.gem/ruby/2.3.1/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'                             
         # /home/alex/.gem/ruby/2.3.1/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'                            
         # /home/alex/.gem/ruby/2.3.1/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'                                         
         # /home/alex/.gem/ruby/2.3.1/gems/rspec_api_documentation-4.9.0/lib/rspec_api_documentation/rack_test_client.rb:38:in `do_request'                                                   
         # /home/alex/.gem/ruby/2.3.1/gems/rspec_api_documentation-4.9.0/lib/rspec_api_documentation/client_base.rb:42:in `process'                                                           
         # /home/alex/.gem/ruby/2.3.1/gems/rspec_api_documentation-4.9.0/lib/rspec_api_documentation/client_base.rb:12:in `get' 
         # ./spec/acceptance/orders_spec.rb:7:in `block (3 levels) in <top (required)>'                                         

    Finished in 0.02056 seconds (files took 0.2384 seconds to load)
    1 example, 1 failure

```

**Comment by victorbrender** [comment]
You are going to have to provide us with more details for us to be able to try and help you. What does your spec_helper.rb contain?

**Comment by mooreniemi** [comment]
FWIW, I just encountered this too. I was playing around with https://github.com/cerebris/peeps and switched it to rspec and RAD.

```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.2)
      actionpack (= 4.2.2)
      actionview (= 4.2.2)
      activejob (= 4.2.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.2)
      actionview (= 4.2.2)
      activesupport (= 4.2.2)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.2)
      activesupport (= 4.2.2)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    activejob (4.2.2)
      activesupport (= 4.2.2)
      globalid (>= 0.3.0)
    activemodel (4.2.2)
      activesupport (= 4.2.2)
      builder (~> 3.1)
    activerecord (4.2.2)
      activemodel (= 4.2.2)
      activesupport (= 4.2.2)
      arel (~> 6.0)
    activesupport (4.2.2)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.3)
    builder (3.2.2)
    coderay (1.1.1)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    diff-lcs (1.3)
    erubis (2.7.0)
    execjs (2.5.2)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    hike (1.2.3)
    i18n (0.7.0)
    jbuilder (1.5.3)
      activesupport (>= 3.0.0)
      multi_json (>= 1.2.0)
    json (1.8.3)
    jsonapi-resources (0.7.0)
      rails (>= 4.0)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    method_source (0.8.2)
    mime-types (2.99)
    mini_portile2 (2.0.0)
    minitest (5.8.3)
    multi_json (1.11.2)
    mustache (1.0.3)
    nokogiri (1.6.7)
      mini_portile2 (~> 2.0.0.rc2)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.2)
      actionmailer (= 4.2.2)
      actionpack (= 4.2.2)
      actionview (= 4.2.2)
      activejob (= 4.2.2)
      activemodel (= 4.2.2)
      activerecord (= 4.2.2)
      activesupport (= 4.2.2)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.2)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    railties (4.2.2)
      actionpack (= 4.2.2)
      activesupport (= 4.2.2)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-rails (3.5.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    rspec_api_documentation (4.8.0)
      activesupport (>= 3.0.0)
      mustache (~> 1.0, >= 0.99.4)
      rspec (~> 3.0, >= 3.0.0)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    slop (3.6.0)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sqlite3 (1.3.10)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)

PLATFORMS
  ruby

DEPENDENCIES
  coffee-rails (~> 4.0.0)
  jbuilder (~> 1.2)
  jsonapi-resources
  pry
  rails (= 4.2.2)
  rspec-rails (~> 3.5)
  rspec_api_documentation
  sass-rails (~> 4.0.2)
  sdoc
  sqlite3
  uglifier (>= 1.3.0)

BUNDLED WITH
   1.14.3
```

**Comment by mooreniemi** [comment]
@victorbrender looks like switching it to `require 'rails_helper'` fixes it, so prob just want to change the official readme: https://github.com/zipmark/rspec_api_documentation#installation ?
