### ISSUE TITLE
Different request header objects between the before block and actual API call

### ISSUE THREAD

**Issue by frankliu81** [zipmark/rspec_api_documentation#390]
I have the folowing example:

```
resource "API v2" do
  
  header "APPLICATION_KEY", "reports"

  before do
    request.headers["HTTP_SOURCE_APPLICATION_KEY"] = "reports"
    binding.pry
  end

  describe "Testing API" do

    get "/api/orgs/:org_id/endpoint" do
      example_request "endpoint" do
        binding.pry
        expect(status).to eq 200
      end
    end

```

I have tried both setting the request.headers directly, or use the header method in the resource block, but neither set the headers properly when I debug inside the application controller.

In my rspec, in the before block.

```
header "APPLICATION_KEY", "reports"

before do 
  request.headers["APPLICATION_KEY"] = "reports" 
  binding.pry
end

```

```
[5] pry(#<RSpec::ExampleGroups::APIV2::Endpoint::GET>)> request.headers["APPLICATION_KEY"]
=> "reports"
[6] pry(#<RSpec::ExampleGroups::APIV2::Endpoint::GET>)> request.headers.object_id
=> 70112185684780
[7] pry(#<RSpec::ExampleGroups::APIV2::Endpoint::GET>)> headers
=> {"Accept"=>"application/vnd.acl.v2+json",
 "AUTHORIZATION"=>"Basic dGVzdDFAZXhhbXBsZS5jb206MTAwMA==\n",
 "APPLICATION_KEY"=>"reports"}
[8] pry(#<RSpec::ExampleGroups::APIV2::Endpoint::GET>)> headers.object_id
=> 70112186141520
```

request.headers and headers  have different object_id.  headers is set by the header method.

Then in the application controller

```
 def ensure_valid_caller!
  # check the request headers
  binding.pry
 end  
```

```
[1] pry(#<Api::V2::Controller>)> request.headers['APPLICATION_KEY']
=> nil

[2] pry(#<Api::V2::Controller>)> request.headers.object_id
=> 70111958577220

[3] pry(#<Api::V2::Controller>)> headers
=> {"X-Frame-Options"=>"SAMEORIGIN",
 "X-XSS-Protection"=>"1; mode=block",
 "X-Content-Type-Options"=>"nosniff"}

[4] pry(#<Api::V2::AccountNewFieldworksController>)> headers.object_id
=> 70112183668180

```

**Issue:** In the controller, the headers and request.headers have different object_id's than what was set in the by header method or request.headers in the before do block.  Therefore, the check for the header value fails in the controller for the spec.

**Comment by frankliu81** [comment]
This is the callstack when the check inside the application controller is hit:

From: /Users/frank_liu/src/projects/app/controllers/api_v2_application_controller.rb @ line 14 ApiV2ApplicationController#ensure_valid_caller!:

    12: def ensure_valid_caller!
    13:   
 => 14:   binding.pry
    15:   unless # check request.headers, but it isn't getting set by header or request.headers
    16:     Rails.logger.fatal "ApiV2ApplicationController::ensure_valid_caller?" \
    17:       " Permission denied"
    18:     raise CanCan::AccessDenied
    19:   end
    20: end

[1] pry(#<Api::V2::Controller>)> caller
=> ["/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:328:in `eval'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:328:in `evaluate_ruby'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:278:in `re'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:254:in `rep'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:234:in `block (3 levels) in repl'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:232:in `loop'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:232:in `block (2 levels) in repl'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:231:in `catch'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:231:in `block in repl'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:230:in `catch'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:230:in `repl'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/pry_class.rb:169:in `start'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-byebug-1.3.2/lib/pry-byebug/pry_ext.rb:15:in `block in start_with_pry_byebug'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-byebug-1.3.2/lib/pry-byebug/processor.rb:21:in `block in run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-byebug-1.3.2/lib/pry-byebug/processor.rb:20:in `catch'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-byebug-1.3.2/lib/pry-byebug/processor.rb:20:in `run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-byebug-1.3.2/lib/pry-byebug/pry_ext.rb:14:in `start_with_pry_byebug'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/pry-0.9.12.6/lib/pry/core_extensions.rb:43:in `pry'",
 "/Users/frank_liu/src/projects/app/controllers/api_v2_application_controller.rb:14:in `ensure_valid_caller!'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in `block in halting'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/searchkick-2.5.0/lib/searchkick/logging.rb:209:in `process_action'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:49:in `serve'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/flipper-0.16.0/lib/flipper/middleware/memoizer.rb:64:in `memoized_call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/flipper-0.16.0/lib/flipper/middleware/memoizer.rb:42:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/flipper-0.16.0/lib/flipper/middleware/setup_env.rb:35:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/warden-1.2.4/lib/warden/manager.rb:35:in `block in call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/etag.rb:24:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/conditionalget.rb:25:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'",
 "/Users/frank_liu/src/projects/config/initializers/webdav.rb:15:in `call'",
 "/Users/frank_liu/src/projects/config/initializers/webdav.rb:15:in `block in <class:ParamsParser>'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/session/abstract/id.rb:225:in `context'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/session/abstract/id.rb:220:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/airbrake-6.1.1/lib/airbrake/rack/middleware.rb:52:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/methodoverride.rb:22:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/runtime.rb:18:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/lock.rb:17:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-1.6.10/lib/rack/sendfile.rb:113:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `get'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec_api_documentation-5.1.0/lib/rspec_api_documentation/rack_test_client.rb:38:in `do_request'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec_api_documentation-5.1.0/lib/rspec_api_documentation/client_base.rb:42:in `process'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec_api_documentation-5.1.0/lib/rspec_api_documentation/client_base.rb:12:in `get'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec_api_documentation-5.1.0/lib/rspec_api_documentation/dsl/endpoint.rb:61:in `do_request'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec_api_documentation-5.1.0/lib/rspec_api_documentation/dsl/endpoint.rb:19:in `block in example_request'"
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `instance_exec'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `block in run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `block in run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:606:in `block in run_around_example_hooks_for'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-rails-3.7.2/lib/rspec/rails/example/controller_example_group.rb:191:in `block (2 levels) in <module:C
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:375:in `execute_with'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:608:in `block (2 levels) in run_around_example_hooks_for'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-rails-3.7.2/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:375:in `execute_with'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:608:in `block (2 levels) in run_around_example_hooks_for'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:609:in `run_around_example_hooks_for'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `with_around_example_hooks'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:251:in `run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:628:in `block in run_examples'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `map'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `run_examples'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:590:in `run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `block in run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `map'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `block in run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `map'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/bin/rspec:22:in `load'",
 "/Users/frank_liu/src/projects/.bundle/ruby/2.3.0/bin/rspec:22:in `<top (required)>'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `load'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `kernel_load'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:28:in `run'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:424:in `exec'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:27:in `dispatch'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:18:in `start'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/bin/bundle:22:in `load'",
 "/Users/frank_liu/.rbenv/versions/2.3.7/bin/bundle:22:in `<main>'"]

**Comment by frankliu81** [comment]
I am working around this issue in my spec by mocking the method for returning the header info in the base API controller using allow_any_instance_of.

**Comment by oestrich** [comment]
Hi @frankliu81 `request` is not available in RAD specs. The only way to modify headers is through the `header` DSL.

What does `request.headers` have in your controller? From what I remember, a bare `headers` in the controller is your response headers. I would expect `request.headers` (in the controller) to have your key. It might be all lower case or some other case than what you're looking for. This is because HTTP headers have no case, so it depends on what rails is doing.

I would expect this to work for you:

```ruby
resource "API v2" do
  header "application_key", "reports"

  describe "Testing API" do
    get "/api/orgs/:org_id/endpoint" do
      let(:org_id) { ... }

      example_request "endpoint" do
        expect(status).to eq 200
      end
    end
  end
end
```

**Comment by frankliu81** [comment]
HI @oestrich ,

I tried to use:

```
resource "API v2" do
  header "application_key", "reports"

  describe "Testing API" do
    get "/api/orgs/:org_id/endpoint" do
      let(:org_id) { ... }

      example_request "endpoint" do
        expect(status).to eq 200
      end
    end
  end
end

```

And if I put a `binding.pry` in the controller, `request.headers["APPLICATION_KEY"]` or `request.headers["application_key"]` is still returning `nil`. 

If I try to see what is in `request.headers`, it simply hangs there for a few minutes and never return.

Since I do have a way of mocking the method in our code that returns the header info in my unit tests, I have just gone with that approach instead.  Thanks.
