### ISSUE TITLE
api_blueprint crashing

### ISSUE THREAD

**Issue by MicMicMon** [zipmark/rspec_api_documentation#416]
While other output formats work well, API Blueprint fails with what follows.

Is it an issue with my test (below) or an issue in the template?

```
NoMethodError: undefined method `route_uri' for #<RSpec::Core::Example "creates user">
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/example.rb:14:in `method_missing'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/views/markup_example.rb:16:in `method_missing'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/views/api_blueprint_index.rb:11:in `block (2 levels) in sections'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/views/api_blueprint_index.rb:11:in `each'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/views/api_blueprint_index.rb:11:in `group_by'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/views/api_blueprint_index.rb:11:in `block in sections'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/views/api_blueprint_index.rb:10:in `map'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/views/api_blueprint_index.rb:10:in `sections'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustache-1.1.0/lib/mustache/context.rb:148:in `call'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustache-1.1.0/lib/mustache/context.rb:148:in `find'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustache-1.1.0/lib/mustache/context.rb:116:in `block in fetch'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustache-1.1.0/lib/mustache/context.rb:112:in `each'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustache-1.1.0/lib/mustache/context.rb:112:in `fetch'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustache-1.1.0/lib/mustache/context.rb:94:in `[]'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustache-1.1.0/lib/mustache/template.rb:46:in `render'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustache-1.1.0/lib/mustache/template.rb:44:in `render'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mustache-1.1.0/lib/mustache.rb:125:in `render'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/writers/general_markup_writer.rb:11:in `block in write'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/writers/general_markup_writer.rb:10:in `open'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/writers/general_markup_writer.rb:10:in `write'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/writers/writer.rb:13:in `write'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/api_documentation.rb:29:in `block in write'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/api_documentation.rb:28:in `each'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/api_documentation.rb:28:in `write'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/api_formatter.rb:38:in `each'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/api_formatter.rb:38:in `stop'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:201:in `block in notify'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:200:in `each'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:200:in `notify'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:194:in `stop'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:167:in `block in finish'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:186:in `close_after'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:166:in `finish'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:76:in `report'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
  /home/mic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/exe/rspec:4:in `<top (required)>'
  /home/mic/.rbenv/versions/2.5.1/bin/rspec:23:in `load'
  /home/mic/.rbenv/versions/2.5.1/bin/rspec:23:in `<top (required)>'
```

```
resource 'Users' do
  explanation 'Users resource'

  header 'Content-Type', 'application/json'

  post '/v1/users', document: :api_v1 do
    parameter :grant_type, "Always set to 'password'", with_example: false, scope: 'user', required: true
    parameter :email, 'User email (login)', scope: 'user', required: true
    parameter :password, 'Plain password', scope: 'user', required: true

    let(:grant_type) { 'password' }
    let(:email) { 'test@email.com' }
    let(:password) { 'passwordtest' }

    example_request 'creates user' do
      expect(response_status).to eq(201)
    end

    # example_request 'Register user' do
    #   expect(response_status).to eq(200)
    #   # byebug
    #   resp = JSON.parse(response_body)
    #   expect(resp['id']&.size).to eq(1)
    # end
  end
end
```

And config:
```
require 'rails_helper'
require 'rspec_api_documentation'
require 'rspec_api_documentation/dsl'

RspecApiDocumentation.configure do |config|
  # Set the application that Rack::Test uses
  config.app = Rails.application

  # Used to provide a configuration for the specification (supported only by 'open_api' format for now) 
  config.configurations_dir = Rails.root.join('doc', 'configurations', 'api')

  # Output folder
  config.docs_dir = Rails.root.join('doc', 'api')

  # An array of output format(s).
  # Possible values are :json, :html, :combined_text, :combined_json,
  #   :json_iodocs, :textile, :markdown, :append_json, :slate,
  #   :api_blueprint, :open_api
  config.format = [:api_blueprint]

  # Location of templates
  #config.template_path = 'inside of the gem'

  # Filter by example document type
  config.filter = :all

  # Filter by example document type
  config.exclusion_filter = nil

  # Used when adding a cURL output to the docs
  config.curl_host = 'https://api.xxxxxxx'

  # Used when adding a cURL output to the docs
  # Allows you to filter out headers that are not needed in the cURL request,
  # such as 'Host' and 'Cookie'. Set as an array.
  config.curl_headers_to_filter = ['Host', 'Cookie']

  # By default, when these settings are nil, all headers are shown,
  # which is sometimes too chatty. Setting the parameters to an
  # array of headers will render *only* those headers.
  config.request_headers_to_include = nil
  config.response_headers_to_include = nil

  # By default examples and resources are ordered by description. Set to true keep
  # the source order.
  config.keep_source_order = false

  # Change the name of the API on index pages
  config.api_name = 'API'
  
  # Change the description of the API on index pages
  config.api_explanation = 'API Description'

  # Redefine what method the DSL thinks is the client
  # This is useful if you need to `let` your own client, most likely a model.
  config.client_method = :client

  # Change the IODocs writer protocol
  config.io_docs_protocol = 'http'

  # You can define documentation groups as well. A group allows you generate multiple
  # sets of documentation.
  config.define_group :public do |config|
    # By default the group's doc_dir is a subfolder under the parent group, based
    # on the group's name.
    config.docs_dir = Rails.root.join('doc', 'api', 'public')

    # Change the filter to only include :public examples
    config.filter = :public
  end

  # Change how the post body is formatted by default, you can still override by `raw_post`
  # Can be :json, :xml, or a proc that will be passed the params
  # config.request_body_formatter = Proc.new { |params| params }
  config.request_body_formatter = :json

  # Change how the response body is formatted by default
  # Is proc that will be called with the response_content_type & response_body
  # by default response_content_type of `application/json` are pretty formated.
  config.response_body_formatter = Proc.new { |response_content_type, response_body| response_body }

  # Change the embedded style for HTML output. This file will not be processed by
  # RspecApiDocumentation and should be plain CSS.
  config.html_embedded_css_file = nil

  # Removes the DSL method `status`, this is required if you have a parameter named status
  config.disable_dsl_status!

  # Removes the DSL method `method`, this is required if you have a parameter named method
  config.disable_dsl_method!
end
```

**Comment by Erol** [comment]
You will need to define a route: https://github.com/zipmark/rspec_api_documentation#api_blueprint

**Comment by MicMicMon** [comment]
Ok thanks, didn't understand it was necessary, I will play around with this part of the doc!
Sorry for the wrong reporting.
Best,

**Comment by ngoral** [comment]
@Erol It's written in docs:

If you don't use `route`, then param in `get(param)` should be an URL as states in the rest of this documentation.

@MicMicMon has it in `post` and so do I in my code. Either documentation is wrong and this does not work or I understand it wrong
