### ISSUE TITLE
Documentation no longer include JSON response body when using with Rack >= 2.1.0

### ISSUE THREAD

**Issue by sikachu** [zipmark/rspec_api_documentation#456]
Hello,

This issue is pretty much for reporting the incompatibility to the gem author, and hopefully it will help anyone who runs into this problem to understand what's going on.

Basically, after we upgrade our dependencies to use Rack 2.1.1, we noticed that our generated documentation no longer show JSON response but instead showing `[binary data]` instead.

Digging in further, we found out that in https://github.com/rack/rack/commit/8c62821f4a464858a6b6ca3c3966ec308d2bb53e, especially [this change](https://github.com/rack/rack/commit/8c62821f4a464858a6b6ca3c3966ec308d2bb53e#diff-4fc9bc1f7d91630f4f9f47fc6663f3f7R195), `MockResponse#body` now creates a buffer and use `<<` to join the content together. However, on line 195, the author uses `String.new` without specifying the encoding, resulting in Ruby creating a [new String with `ASCII-8BIT` encoding by default](https://ruby-doc.org/core-2.7.0/String.html#method-c-new).

As it turns out, rspec_api_documentation relies on string encoding to determine if it should include the response body in the documentation or not:

https://github.com/zipmark/rspec_api_documentation/blob/560c3bdc7bd5581e7c223334390221ecfc910be8/lib/rspec_api_documentation/client_base.rb#L90-L95

Hence, the change in Rack broke this conditional.

I've reported this issue to Rack in https://github.com/rack/rack/pull/1486, and hopefully we can solve this soon.

The solution right now for us is to lock Rack to `~> 2.0.8` for now.

Thank you very much.

**Comment by FrankFang** [comment]
Any other workaround?

**Comment by Tao-Galasse** [comment]
I ran into the same issue recently. I don't really like this solution, but I fixed it using mokey patching:
`config/initializers/rspec_api_documentation.rb`
```
module RspecApiDocumentation
  class  RackTestClient < ClientBase
    def response_body
      last_response.body.encode("utf-8")
    end
  end
end
```

**Comment by eimermusic** [comment]
This seems to also be the result after Rails 6 upgrade.

**Comment by bitlather** [comment]
Just created a new rails 6 app and had this problem, Tao's response above fixed it (https://github.com/zipmark/rspec_api_documentation/issues/456#issuecomment-597671587)

**Comment by cpursley** [comment]
@Tao-Galasse solution worked.

I found that I needed to stick it right before the `RspecApiDocumentation.configure` block instead of the initializers directory.

**Comment by skibox** [comment]
There's an additional issue with endpoints that use `send_data`:

```
     Failure/Error: last_response.body.encode("utf-8")
     
     Encoding::UndefinedConversionError:
       "\xD3" from ASCII-8BIT to UTF-8
     # ./config/initializers/rspec_api_documentation.rb:6:in `encode'
     # ./config/initializers/rspec_api_documentation.rb:6:in `response_body'
```

I've tweaked Tao's fix, it ain't perfect but it works for my projects:
```
module RspecApiDocumentation
  class RackTestClient < ClientBase
    def response_body
      if last_response.headers["Content-Type"].include?("json")
        last_response.body.encode("utf-8")
      else
        "[binary data]"
      end
    end
  end
end
```

**Comment by ShamoX** [comment]
On my side, I fixed it by two mechanisms :
1. @skibox's @Tao-Galasse solution remade mine
2. Use `response_body_formatter` like it is intended to filter the different kind of output and make it OK for `apitome`

Resulting in this `spec/support/rspec_api_documentation.rb` file :
```
# frozen_string_literal: true

# Fix a bug that generate erroneous "[binary data]" not yet fixed on rspec_api_documentation:6.1.0
module RspecApiDocumentation
  class RackTestClient < ClientBase
    def response_body
      body = last_response.body
      if body.empty? || last_response.headers['Content-Type'].include?('json')
        body.encode('utf-8')
      else
        '"[binary data]"'
      end
    rescue Encoding::UndefinedConversionError
      '"[binary data]"'
    end
  end
end

# configure rspec_api_documentation
RspecApiDocumentation.configure do |config|
# ..... some unrelated config here  

  # Change how the response body is formatted by default
  # Is proc that will be called with the response_content_type & response_body
  # by default response_content_type of `application/json` are pretty formated.
  config.response_body_formatter = lambda do |response_content_type, response_body|
    if response_content_type.include?('application/json')
      JSON.parse(response_body)
      return response_body
    elsif response_content_type.include?('text') || response_content_type.include?('txt')
      # quote it for JSON Parser in documentation reader like APITOME
      return "\"#{response_body}\""
    else
      return '"[binary data]"'
    end
  rescue JSON::ParseError
    '"[binary data]"'
  end

# ... Other unrelated config
end

```

**Comment by davidstosik** [comment]
Just to make sure people notice, this issue would be fixed by https://github.com/zipmark/rspec_api_documentation/pull/458 🙇‍♂️

**Comment by jakehow** [comment]
For anyone following this, Ive merged #458 please let me know if this resolves the issue for you.  cc @artofhuman

**Comment by Uysim** [comment]
Hope this can be fixed. We need to work with Rails 6

**Comment by jakehow** [comment]
@Uysim please test and let everyone know

**Comment by incubus** [comment]
Doesn't work with application/vnd.api+json content type.

**Comment by davidstosik** [comment]
@incubus I believe the change that was merged in #458 should work with `application/vnd.api+json`.

See this line:

https://github.com/zipmark/rspec_api_documentation/blob/d3892cc7388460a98476734963face5a7a2ac158/lib/rspec_api_documentation/configuration.rb#L123

The regular expression `/application\/.*json/` matches the string `application/vnd.api+json`, so the content should be identified as JSON and prettyfied.

Can you please make sure you use the `master` branch (at least until there's a new release)?

**Comment by incubus** [comment]
@davidstosik it works, thanks!

**Comment by daviidy** [comment]
> I ran into the same issue recently. I don't really like this solution, but I fixed it using mokey patching:
> `config/initializers/rspec_api_documentation.rb`
> 
> ```
> module RspecApiDocumentation
>   class RackTestClient < ClientBase
>     def response_body
>       last_response.body.encode("utf-8")
>     end
>   end
> end
> ```
> 
> Indeed, it seems to be caused by an encoding issue where utf-8 become ascii-8bit

It worked for me. Thank you so much

**Comment by DakotaLMartinez** [comment]
> # frozen_string_literal: true
> 
> # Fix a bug that generate erroneous "[binary data]" not yet fixed on rspec_api_documentation:6.1.0
> module RspecApiDocumentation
>   class RackTestClient < ClientBase
>     def response_body
>       body = last_response.body
>       if body.empty? || last_response.headers['Content-Type'].include?('json')
>         body.encode('utf-8')
>       else
>         '"[binary data]"'
>       end
>     rescue Encoding::UndefinedConversionError
>       '"[binary data]"'
>     end
>   end
> end

I did a slight variation on this one so I could get the responses to show up as pretty printed:

```rb
RspecApiDocumentation.configure do |config|
  config.response_body_formatter = lambda do |response_content_type, response_body|
    if response_content_type.include?('application/json')
      return JSON.pretty_generate(JSON.parse(response_body))
    elsif response_content_type.include?('text') || response_content_type.include?('txt')
      # quote it for JSON Parser in documentation reader like APITOME
      return "\"#{response_body}\""
    else
      return '"[binary data]"'
    end
  rescue JSON::ParseError
    '"[binary data]"'
  end
end
```
