### ISSUE TITLE
Support ruby 3.2, DEPRECATED File.exists?

### ISSUE THREAD

**Issue by sandraa-nestor** [zipmark/rspec_api_documentation#514]
When I try to generate api docs on ruby 3.2.0 I get an error:

`../lib/rspec_api_documentation/writers/writer.rb:17:in 'clear_docs': undefined method 'exists?' for File:Class (NoMethodError)`

`File.exists?` was deprecated in ruby 2.1.0 and has been removed in the ruby 3.2.0

**Comment by nickmerwin** [comment]
As a workaround, you can add a monkey-patch like:

```ruby
class File
  class << self
    alias_method :exists?, :exist?
  end
end
```

**Comment by pjscopeland** [comment]
Rubocop removes the line entirely as `File.rm_rf` is supposed to be idempotent and not care if the file doesn't exist

**Comment by olleolleolle** [comment]
The latest CI runs also on Ruby 3.3, is this an issue any longer?

**Comment by sergiytopchiy** [comment]
> The latest CI runs also on Ruby 3.3, is this an issue any longer?

Yes it is. Ruby 3.3.2
```rake docs:generate
/home/serhii/.rvm/rubies/ruby-3.3.2/bin/ruby -I/home/serhii/.rvm/gems/ruby-3.3.2/gems/rspec-core-3.13.3/lib:/home/serhii/.rvm/gems/ruby-3.3.2/gems/rspec-support-3.13.2/lib /home/serhii/.rvm/gems/ruby-3.3.2/gems/rspec-core-3.13.3/exe/rspec --pattern spec/acceptance/\*\*/\*_spec.rb --format RspecApiDocumentation::ApiFormatter
Generating API Docs
/home/serhii/.rvm/gems/ruby-3.3.2/gems/rspec_api_documentation-6.1.0/lib/rspec_api_documentation/writers/writer.rb:17:in `clear_docs': undefined method `exists?' for class File (NoMethodError)

        if File.exists?(docs_dir)
               ^^^^^^^^
Did you mean?  exist?```
